config/routes.rb
Vinegar::Application.routes.draw do
  devise_for :admins

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :markers, :only => [:index, :create, :show]

  root :to => 'home#index'

  get 'charts' => 'chart#index'

  get 'markers24h' => 'markers#markers_in_the_last_24h'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/marker.rb
class Marker < ActiveRecord::Base
  attr_accessible :latitude, :longitude, :marker_type, :description

  validates_presence_of :latitude
  validates_presence_of :longitude

  scope :created_in_last_30min, lambda { {:conditions => ["created_at > ?", 31.minutes.ago ] } }
  scope :created_in_last_24h, lambda { {:conditions => ["created_at > ?", 24.hours.ago ] } }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chart_controller.rb
class ChartController < ApplicationController
	def index
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  # GET /markers
  # GET /markers.json
  def index
    @markers = Marker.created_in_last_30min.all

    respond_to do |format|
      format.html # index.html.erb
      format.json {
        render json: @markers.to_json(:only => [:id, :latitude, :longitude, :marker_type, :description])
      }
    end
  end

  def markers_in_the_last_24h
    @markers_last_24h = Marker.created_in_last_24h.all

    respond_to do |format|
      format.html
      format.json {
        render json: @markers_last_24h.to_json(:only => [:latitude, :longitude, :marker_type, :description])
      }
    end
  end

  # GET /markers/1
  # GET /markers/1.json
  def show
    @marker = Marker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @marker }
    end
  end

  # GET /markers/new
  # GET /markers/new.json
  def new
    @marker = Marker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @marker }
    end
  end

  # GET /markers/1/edit
  def edit
    @marker = Marker.find(params[:id])
  end

  # POST /markers
  # POST /markers.json
  def create
    @marker = Marker.new(params[:marker])

    respond_to do |format|
      if @marker.save
        format.html { redirect_to @marker, notice: 'Marker was successfully created.' }
        format.json { render json: @marker, status: :created, location: @marker }
      else
        format.html { render action: "new" }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /markers/1
  # PUT /markers/1.json
  def update
    @marker = Marker.find(params[:id])

    respond_to do |format|
      if @marker.update_attributes(params[:marker])
        format.html { redirect_to @marker, notice: 'Marker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markers/1
  # DELETE /markers/1.json
  def destroy
    @marker = Marker.find(params[:id])
    @marker.destroy

    respond_to do |format|
      format.html { redirect_to markers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chart_helper.rb
module ChartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/views/chart/index.html.erb
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  // Load the Visualization API and the piechart package.
  google.load('visualization', '1.0', {'packages':['corechart']});

  // Set a callback to run when the Google Visualization API is loaded.
  google.setOnLoadCallback(loadMarkerData);

  // Callback that creates and populates a data table,
  // instantiates the pie chart, passes in the data and
  // draws it.
  function drawChart(dataArray) {

    // Create the data table.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Topping');
    data.addColumn('number', 'Slices');
    data.addRows([
      ['Mushrooms', 3],
      ['Onions', 1],
      ['Olives', 1],
      ['Zucchini', 1],
      ['Pepperoni', 2]
    ]);

    // Set chart options
    var options = {'title':'How Much Pizza I Ate Last Night',
                   'width':400,
                   'height':300};

    // Instantiate and draw our chart, passing in some options.
    var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
    chart.draw(data, options);
  }

  function loadMarkerData() {
    $.ajax({
      type: "GET",
      url: "/markers24h",
      data: { format: "json" },
      success: function (markersarray) {
        drawChart(markersarray);
      },
      error: function (data) {
        console.log(data.response)
      }
    });
  }
</script> 
 <div id="chart_div"></div>

app/views/home/index.html.erb
<style type="text/css">
  #app-title {
    position: absolute;
    width: 100%;
    top: 0px;
    background-color: #fa5a25;
    z-index: 10;
  }

  #menu {
    position: absolute;
    width: 100%;
    width: 100%;
    left: 0px;
    bottom: 5px;
  }

  #menu-toggle {
    position: relative;
    z-index: 3;
  }

  #loading {
    position: absolute;
    top:50%;
    z-index:1;
    background-color: #fa5a25;
    width: 100%;
    text-align: center;
  }

  #menu-items {
    position: relative;
    z-index: 4;
  }

  .menu-handle-icon {
    position: relative;
    z-index: 4;
  }

  .menu-items-top img {
    margin-left: -3px;
    margin-right: -3px;
    margin-bottom: -25px;
    height: 100%;
  }

  .menu-items-down img {
    margin-left: -3px;
    margin-right: -3px;
    margin-bottom: 0px;
  }

  .menuitem {
  }

  .expanded {
  }

  .collapsed {
  }

</style>

<div id="app-title" class="text-center">
  <%= image_tag "logo.png", {id: 'img-logo'} %>
</div>

<div id="menu" class="text-center collapsed">
  <div id="menu" class="text-center collapsed">
    <%= image_tag "btn_button_alert_main_normal.png", {class: "menu-handle-icon"} %>
    <div id="menu-items" class="text-center">
      <div class="menu-items-top">
        <%= image_tag "btn_alert_police_normal.png", {class: "menuitem", id: "btn-policia"} %>
        <%= image_tag "btn_alert_conflict_normal.png", {class: "menuitem", id: "btn-conflito"} %>
      </div>
      <div class="menu-items-down">
        <%= image_tag "btn_alert_meetingpoint_normal.png", {class: "menuitem", id: "btn-encontro"} %>
        <%= image_tag "btn_button_alert_main_pressed.png", {class: "menu-handle-icon-pressed"} %>
        <%= image_tag "btn_alert_depredation_normal.png", {class: "menuitem", id: "btn-depedracao"} %>
      </div>
    </div>
  </div>
</div>
<div id="loading">Carregando mapa...</div>
<div id="map_canvas" class="map"/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gigante Alerta</title>
  <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.9.0/build/reset/reset-min.css">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
  <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=AIzaSyAWnf__qwiQovUH_nGkODWdyS4wD4kZ9wY&sensor=true"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-capable" content="yes">
</head>
<body>

<%= yield %>

<%= javascript_include_tag "application" %>
</body>
</html>

app/views/markers/_form.html.erb
<%= form_for(@marker) do |f| %>
  <% if @marker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@marker.errors.count, "error") %> prohibited this marker from being saved:</h2>

      <ul>
      <% @marker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :marker_type %><br />
    <%= f.text_field :marker_type %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/markers/edit.html.erb
<h1>Editing marker</h1>

<%= render 'form' %>

<%= link_to 'Show', @marker %> |
<%= link_to 'Back', markers_path %>

app/views/markers/index.html.erb
<h1>Listing markers</h1>

<table>
  <tr>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @markers.each do |marker| %>
  <tr>
    <td><%= marker.latitude %></td>
    <td><%= marker.longitude %></td>
    <td><%= link_to 'Show', marker %></td>
    <td><%= link_to 'Edit', edit_marker_path(marker) %></td>
    <td><%= link_to 'Destroy', marker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Marker', new_marker_path %>

app/views/markers/new.html.erb
<h1>New marker</h1>

<%= render 'form' %>

<%= link_to 'Back', markers_path %>

app/views/markers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Latitude:</b>
  <%= @marker.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @marker.longitude %>
</p>

<p>
  <b>Type:</b>
  <%= @marker.marker_type %>
</p>

<p>
  <b>Description:</b>
  <%= @marker.description %>
</p>

<%= link_to 'Edit', edit_marker_path(@marker) %> |
<%= link_to 'Back', markers_path %>